name: wygw
channels:
  - conda-forge
  - defaults
dependencies:
  - affine=2.3.0=py_0
  - flopy=3.3.0=py37h5ca1d4c_0
  - gdal=3.0.4=py37hd44be9e_6
  - geopandas=0.6.1=py_0
  - matplotlib=3.1.3=py37_0
  - matplotlib-base=3.1.3=py37h64f37c6_0
  - netcdf4=1.5.3=nompi_py37h727d961_103
  - numpy=1.18.1=py37h93ca92e_0
  - numpy-base=1.18.1=py37hc3f5095_1
  - numpydoc=0.9.2=py_0
  - pandas=1.0.3=py37h47e9c7a_0
  - pandoc=2.2.3.2=0
  - pandocfilters=1.4.2=py37_1
  - pyshp=2.1.0=py_0
  - rasterio=1.1.0=py37h039b02d_0
  - scipy=1.4.1=py37h9439919_0